# Generated by Django 4.1.7 on 2023-04-07 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scores_round_1',
            old_name='student',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='scores_round_2',
            old_name='student',
            new_name='Student',
        ),
    ]
