# Generated by Django 4.1.7 on 2023-04-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_student_scores_round_1_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores_round_1',
            name='communication_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scores_round_1',
            name='presentation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scores_round_1',
            name='research_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scores_round_2',
            name='communication_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scores_round_2',
            name='presentation_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scores_round_2',
            name='research_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
